/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/poi-lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poi Lookup
         * @description 批量查询 POI 坐标和地址。
         *
         *     前端传入城市 + 名称列表，后端调用高德 POI 搜索 API，
         *     返回每个名称的坐标和地址。未找到的名称列入 failed 列表，
         *     若跨城市则附带建议地址。
         */
        post: operations["poi_lookup_api_poi_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest
         * @description 获取方案建议列表。
         *
         *     不指定 n_days，run_planning 内部回退到 ca_suggest()，
         *     遍历多种聚类方法 × 天数，返回 top-5 建议。
         */
        post: operations["suggest_api_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan
         * @description 执行完整规划，返回 3D 地图 HTML 和每日行程。
         *
         *     n_days 为必填，mode 可选 "fast"(CA) 或 "deep"(VNS)。
         */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description LLM Agent 对话接口，SSE 流式输出。
         *
         *     Mock 模式返回死 token，方便前端联调。
         *     正式上线后设置 MOCK_MODE=False 即可切换 DeepSeek 真实调用。
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description LLM Agent 对话请求。
         *
         *     message: 用户输入的消息。
         *     plan_result: 可选的规划结果上下文，供 Agent 参考。
         */
        ChatRequest: {
            /**
             * Message
             * @description 用户输入的消息
             */
            message: string;
            /**
             * Plan Result
             * @description 规划结果上下文
             */
            plan_result?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * POIItem
         * @description 单个景点数据模型。
         *
         *     Attributes:
         *         name: 景点名称（用于显示和 API 查询）。
         *         lon: 经度（GCJ-02 坐标系，与高德 API 一致）。
         *         lat: 纬度。
         *         tw_start: 时间窗开始，距午夜分钟数（默认 480 = 8:00）。
         *         tw_end: 时间窗结束，距午夜分钟数（默认 1020 = 17:00）。
         *         stay: 建议停留时长（分钟），影响时间窗有效结束时间。
         *         expected_arrival: 用户期望到达时间，可为空。
         */
        POIItem: {
            /** Name */
            name: string;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /**
             * Tw Start
             * @description 营业开始时间，距午夜分钟数
             * @default 480
             */
            tw_start: number;
            /**
             * Tw End
             * @description 营业结束时间，距午夜分钟数
             * @default 1020
             */
            tw_end: number;
            /**
             * Stay
             * @description 停留时间，分钟
             * @default 0
             */
            stay: number;
            /**
             * Expected Arrival
             * @description 预期到达时间，距午夜分钟数
             */
            expected_arrival?: number | null;
        };
        /**
         * POILookupItem
         * @description 单个 POI 查询结果。
         *
         *     tw_start/tw_end 由 LLM 解析 opentime2 后返回，
         *     前端不再硬编码默认营业时间。
         */
        POILookupItem: {
            /** Name */
            name: string;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Address */
            address: string;
            /**
             * Tw Start
             * @description 营业开始分钟数，0-1440，LLM 解析
             */
            tw_start?: number | null;
            /**
             * Tw End
             * @description 营业结束分钟数，0-1440，LLM 解析
             */
            tw_end?: number | null;
        };
        /**
         * POILookupRequest
         * @description POI 坐标/地址查询请求。
         *
         *     调用高德 POI 搜索 API 批量获取坐标和地址。
         *     酒店也作为普通 POI 查询，前端根据名称匹配区分。
         */
        POILookupRequest: {
            /** City */
            city: string;
            /**
             * Names
             * @description POI 名称列表（酒店+景点）
             */
            names: string[];
        };
        /**
         * POILookupResponse
         * @description POI 查询响应。
         *
         *     items: 查询成功的 POI 列表。
         *     failed: 未找到的 POI 名称列表。
         */
        POILookupResponse: {
            /** Items */
            items: components["schemas"]["POILookupItem"][];
            /** Failed */
            failed: string[];
        };
        /**
         * PlanRequest
         * @description 统一请求模型，适用于 /api/suggest 和 /api/plan。
         *
         *     包含酒店信息、景点列表和算法参数。
         *     n_days 为 None 时返回方案建议（ca_suggest），否则返回完整方案。
         *
         *     Attributes:
         *         city: 城市名（用于文件命名和显示）。
         *         hotel_name: 酒店名称。
         *         hotel_lon/lat: 酒店坐标（GCJ-02）。
         *         hotel_tw_start/end: 酒店时间窗（默认 0:00~24:00）。
         *         spots: 景点列表，至少 1 个。
         *         n_days: 行程天数。None 时走建议模式，有值时走规划模式。
         *         mode: "fast"(CA) 或 "deep"(VNS)。
         *         day_start: 一天启程时间，对所有景点生效（默认 0 = 午夜）。
         *         penalty_weight: 迟到惩罚权重。
         *         early_wait_weight: 早到等待惩罚权重。
         *         late_return_weight: 晚归惩罚权重。
         */
        PlanRequest: {
            /** City */
            city: string;
            /** Hotel Name */
            hotel_name: string;
            /** Hotel Lon */
            hotel_lon: number;
            /** Hotel Lat */
            hotel_lat: number;
            /**
             * Hotel Tw Start
             * @description 酒店开放时间开始，距午夜分钟数（默认 0 = 全天）
             * @default 0
             */
            hotel_tw_start: number;
            /**
             * Hotel Tw End
             * @description 酒店开放时间结束，距午夜分钟数（默认 1440 = 24:00）
             * @default 1440
             */
            hotel_tw_end: number;
            /**
             * Min Days
             * @description 搜索最小天数，不传由引擎自动推断
             */
            min_days?: number | null;
            /**
             * Max Days
             * @description 搜索最大天数，不传由引擎自动推断
             */
            max_days?: number | null;
            /**
             * Spots
             * @description 景点列表，至少 1 个
             */
            spots: components["schemas"]["POIItem"][];
            /**
             * N Days
             * @description 行程天数，None 时返回建议
             */
            n_days?: number | null;
            /**
             * Mode
             * @description 求解模式：fast(CA) 或 deep(VNS)
             * @default fast
             */
            mode: string;
            /**
             * Day Start
             * @description 一天启程时间（距午夜分钟数），0=午夜
             * @default 0
             */
            day_start: number;
            /**
             * Penalty Weight
             * @description 迟到惩罚权重（默认 100.0）
             * @default 100
             */
            penalty_weight: number;
            /**
             * Early Wait Weight
             * @description 早到等待惩罚权重（默认 0.1）
             * @default 0.1
             */
            early_wait_weight: number;
            /**
             * Late Return Weight
             * @description 晚归惩罚权重（默认 50.0）
             * @default 50
             */
            late_return_weight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    poi_lookup_api_poi_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["POILookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["POILookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
