"""create users and add user_id

Revision ID: 30d2fa80d5e2
Revises: 3c7f2a91b5e8
Create Date: 2026-08-27 13:49:12.341032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d2fa80d5e2'
down_revision: Union[str, Sequence[str], None] = '3c7f2a91b5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment='user/guest/admin'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='登录邮箱（guest 为 NULL）'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希（guest 为 NULL）'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedback_records', sa.Column('user_id', sa.UUID(), nullable=True, comment='归属用户（可空）'))
    op.create_index(op.f('ix_feedback_records_user_id'), 'feedback_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'feedback_records', 'users', ['user_id'], ['id'])
    op.add_column('history_records', sa.Column('user_id', sa.UUID(), nullable=True, comment='归属用户（可空=存量匿名；单一归属键）'))
    op.create_index(op.f('ix_history_records_user_id'), 'history_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'history_records', 'users', ['user_id'], ['id'])
    op.add_column('plan_tasks', sa.Column('user_id', sa.UUID(), nullable=True, comment='归属用户（可空）'))
    op.create_index(op.f('ix_plan_tasks_user_id'), 'plan_tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'plan_tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_plan_tasks_user_id'), table_name='plan_tasks')
    op.drop_column('plan_tasks', 'user_id')
    op.drop_constraint(None, 'history_records', type_='foreignkey')
    op.drop_index(op.f('ix_history_records_user_id'), table_name='history_records')
    op.drop_column('history_records', 'user_id')
    op.drop_constraint(None, 'feedback_records', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_records_user_id'), table_name='feedback_records')
    op.drop_column('feedback_records', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
